EXTENSIVE WORK ON MY-ROLES
 - Remove pipes to "true" and instead set failed_when to exempt the
   expected return codes from setting the failure state.

 - Use "|&" for piping stdout and stderr to sed rather than "2>&1 |".
   It's just a little briefer.

 - Use "&>>" to redirect stderr in addition to stdin to the common log
   file. Failure to do this was resulting in the termination of at least
   one process launched with nohup when the parent shell closed.

 - Separate out the check that a process has started into a separate
   Ansible step. This ensures that the process has survived the closing
   of the shell that launched it.

 - Raise a shell error condition when the "process has started" checks
   fail.

 - Don't specify full path to executables where they are in the
   executable path anyway.

 - Correct missing '-f' flag to pgrep command.

 - Cater for Debian stretch in the my_database role.

 - nohup shell to run mysqld_safe command as it doesn't appear to
   survive the shell closing if it's launch directly from the shell that
   closed.

 - Correct error whereby fetchmailrc_exists object was tested rather
   than its rc attribute.

 - Add creation of the Apache run directory in the my_wordpress_apache
   role when starting the process. Without this the start fails.

 - Correct error whereby check on whether php-fpm has started
   successfully or not incorrectly matched 'php-fpm: master process' as
   the whole process string. In actual fact there's more that follows.

 - Fix dependency chain in wordpress_apache/wordpress_nginx -> wordpress
   -> mta, which uses latest changes in libraries_ansible submodule and
   also involved creation of main task list in my_wordpress role.

diff --git a/my-roles/my_calendar/tasks/start-radicale.yml b/my-roles/my_calendar/tasks/start-radicale.yml
--- a/my-roles/my_calendar/tasks/start-radicale.yml
+++ b/my-roles/my_calendar/tasks/start-radicale.yml
@@ -12,42 +12,53 @@
 - name: Test if the radicale process is running
   ansible.builtin.shell: |-
     {% if lsb_release.stdout == 'buster' %}
-    pgrep -f '^/usr/bin/python3 /usr/bin/radicale -f$' || true
+    pgrep -f '^python3 /usr/bin/radicale -f$'
     {% elif lsb_release.stdout == 'bullseye' %}
-    pgrep -f '^/usr/bin/python3 /usr/bin/radicale$' || true
+    pgrep -f '^python3 /usr/bin/radicale$'
     {% endif %}
   register: pgrep_result
   changed_when: false
+  failed_when: pgrep_result.rc !=0 and pgrep_result.rc != 1
 
-- name: Start the radicale process
-  ansible.builtin.shell: |-
-    echo 'radicale   : Starting' >> /var/local/services.log
-    {% if lsb_release.stdout == 'buster'%}
-    nohup /usr/bin/radicale -f 2>&1 | sed -u 's/^/radicale   : /' \
-      >> /var/local/services.log &
-    {% elif lsb_release.stdout == 'bullseye' %}
-    nohup /usr/bin/radicale 2>&1 | sed -u 's/^/radicale   : /' \
-      >> /var/local/services.log &
-    {% endif %}
+- block:
 
-    n=0
-    while [ $n -lt 3 ]; do
-      sleep 3
-      {% if lsb_release.stdout == 'buster'%}
-      pgrep -f '^/usr/bin/python3 /usr/bin/radicale -f$' && \
-        echo 'radicale   : Started' >> /var/local/services.log && break
-      {% elif lsb_release.stdout == 'bullseye' %}
-      pgrep '^/usr/bin/python3 /usr/bin/radicale$' && \
-        echo 'radicale   : Started' >> /var/local/services.log && break
-      {% endif %}
-      let n=n+1
-    done
+    - name: Start the radicale process
+      ansible.builtin.shell: |-
+        echo 'radicale   : Starting' >> /var/local/services.log
+        {% if lsb_release.stdout == 'buster' %}
+        nohup radicale -f |& sed -u 's/^/radicale   : /' \
+          &>> /var/local/services.log &
+        {% elif lsb_release.stdout == 'bullseye' %}
+        nohup radicale |& sed -u 's/^/radicale   : /' \
+          &>> /var/local/services.log &
+        {% endif %}
+      args:
+        executable: /bin/bash
+      become: yes
 
-    if [ $n -eq 3 ]; then
-      echo 'radicale   : Failed to start process' \
-        >> /var/local/services.log
-    fi
-  args:
-    executable: /bin/bash
-  become: yes
-  when: not pgrep_result.stdout
+    - name: Check the radicale process has started
+      # We do this in a separate shell task to the one that we started the
+      # process in so that we know that the process survived beyond that shell.
+      ansible.builtin.shell: |
+        n=0
+        while [ $n -lt 3 ]; do
+          sleep 3
+          {% if lsb_release.stdout == 'buster' %}
+          pgrep -f '^/usr/bin/python3 /usr/bin/radicale -f$' && \
+            echo 'radicale   : Started' >> /var/local/services.log && break
+          {% elif lsb_release.stdout == 'bullseye' %}
+          pgrep -f '^/usr/bin/python3 /usr/bin/radicale$' && \
+            echo 'radicale   : Started' >> /var/local/services.log && break
+          {% endif %}
+          let n=n+1
+        done
+
+        if [ $n -eq 3 ]; then
+          echo 'radicale   : Failed to start process' \
+            >> /var/local/services.log
+          exit 1
+        fi
+      args:
+        executable: /bin/bash
+
+  when: pgrep_result.rc == 1
diff --git a/my-roles/my_database/tasks/start-mysql.yml b/my-roles/my_database/tasks/start-mysql.yml
--- a/my-roles/my_database/tasks/start-mysql.yml
+++ b/my-roles/my_database/tasks/start-mysql.yml
@@ -11,54 +11,64 @@
 
 - name: Test if the mysqld (buster) or mariadb (bullseye) process is running
   ansible.builtin.shell: |-
-    {% if lsb_release.stdout == 'buster' %}
-    pgrep -f '^/usr/sbin/mysqld' || true
-    {% elif lsb_release.stdout == 'bullseye' %}
-    pgrep -f '^/usr/sbin/mariadbd' || true
+    {% if lsb_release.stdout == 'bullseye' %}
+    pgrep -f '^/usr/sbin/mariadbd'
+    {% else %}{# buster or stretch #}
+    pgrep -f '^/usr/sbin/mysqld'
     {% endif %}
   register: pgrep_result
   changed_when: false
+  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1
 
-- name: Start the mysqld (buster) or mariadb (bullseye) process
-  ansible.builtin.shell: |-
-    {% if lsb_release.stdout == 'buster' %}
+- block:
 
-    echo 'mysqld     : Starting' >> /var/local/services.log
-    nohup mysqld_safe 2>&1 | sed -u 's/^/mysqld     : /' \
-      >> /var/local/services.log &
+    - name: Start the mysqld (buster) or mariadb (bullseye) process
+      ansible.builtin.shell: |-
+        {% if lsb_release.stdout == 'bullseye' %}
+        echo 'mariadbd   : Starting' >> /var/local/services.log
+        nohup bash -c "mysqld_safe |& sed -u 's/^/mariadbd   : /'" \
+          &>> /var/local/services.log &
+        {% else %}{# buster or stretch #}
+        echo 'mysqld     : Starting' >> /var/local/services.log
+        nohup bash -c "mysqld_safe |& sed -u 's/^/mysqld     : /'" \
+          &>> /var/local/services.log &
+        {% endif %}
+      args:
+        executable: /bin/bash
+      become: yes
 
-    n=0
-    while [ $n -lt 3 ]; do
-      sleep 3
-      pgrep -f '^/usr/sbin/mysqld' && \
-        echo 'mysqld     : Started' >> /var/local/services.log && break
-      let n=n+1
-    done
+    - name: Check the mysqld (buster) or mariadb (bullseye) process has started
+      # We do this in a separate shell task to the one that we started the
+      # process in so that we know that the process survived beyond that shell.
+      ansible.builtin.shell: |-
+        {% if lsb_release.stdout == 'bullseye' %}
+        n=0
+        while [ $n -lt 3 ]; do
+          sleep 3
+          pgrep -f '^/usr/sbin/mariadbd' && \
+            echo 'mariadbd   : Started' >> /var/local/services.log && break
+          let n=n+1
+        done
 
-    if [ $n -eq 3 ]; then
-      echo 'mysqld     : Failed to start process' >> /var/local/services.log
-    fi
+        if [ $n -eq 3 ]; then
+          echo 'mariadbd   : Failed to start process' >> /var/local/services.log
+          exit 1
+        fi
+        {% else %}{# buster or stretch #}
+        n=0
+        while [ $n -lt 3 ]; do
+          sleep 3
+          pgrep -f '^/usr/sbin/mysqld' && \
+            echo 'mysqld     : Started' >> /var/local/services.log && break
+          let n=n+1
+        done
 
-    {% elif lsb_release.stdout == 'bullseye' %}
+        if [ $n -eq 3 ]; then
+          echo 'mysqld     : Failed to start process' >> /var/local/services.log
+          exit 1
+        fi
+        {% endif %}
+      args:
+        executable: /bin/bash
 
-    echo 'mariadbd   : Starting' >> /var/local/services.log
-    nohup mysqld_safe 2>&1 | sed -u 's/^/mariadbd   : /' \
-      >> /var/local/services.log &
-
-    n=0
-    while [ $n -lt 3 ]; do
-      sleep 3
-      pgrep -f '^/usr/sbin/mariadbd' && \
-        echo 'mariadbd   : Started' >> /var/local/services.log && break
-      let n=n+1
-    done
-
-    if [ $n -eq 3 ]; then
-      echo 'mariadbd   : Failed to start process' >> /var/local/services.log
-    fi
-
-    {% endif %}
-  args:
-    executable: /bin/bash
-  become: yes
-  when: not pgrep_result.stdout
+  when: pgrep_result.rc == 1
diff --git a/my-roles/my_dns/tasks/start-dnsmasq.yml b/my-roles/my_dns/tasks/start-dnsmasq.yml
--- a/my-roles/my_dns/tasks/start-dnsmasq.yml
+++ b/my-roles/my_dns/tasks/start-dnsmasq.yml
@@ -6,29 +6,40 @@
 
 - name: Test if the dnsmasq process is running
   ansible.builtin.shell: |-
-    pgrep -f '^dnsmasq -d$' || true
+    pgrep -f '^dnsmasq -d$'
   register: pgrep_result
   changed_when: false
+  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1
 
-- name: Start the dnsmasq process
-  ansible.builtin.shell: |-
-    echo 'dnsmasq    : Starting' >> /var/local/services.log
-    nohup dnsmasq -d 2>&1 \
-      | sed -u 's/^\(dnsmasq: \)\?/dnsmasq    : /' >> /var/local/services.log &
+- block:
 
-    n=0
-    while [ $n -lt 3 ]; do
-      sleep 3
-      pgrep -f '^dnsmasq -d$' && 
-        echo 'dnsmasq    : Started' >> /var/local/services.log && break
-      let n=n+1
-    done
-    
-    if [ $n -eq 3 ]; then
-      echo 'dnsmasq    : Failed to start process' \
-        >> /var/local/services.log
-    fi
-  args:
-    executable: /bin/bash
-  become: yes
-  when: not pgrep_result.stdout
+    - name: Start the dnsmasq process
+      ansible.builtin.shell: |-
+        echo 'dnsmasq    : Starting' >> /var/local/services.log
+        nohup dnsmasq -d |& \ sed -u 's/^\(dnsmasq: \)\?/dnsmasq    : /' \
+          &>> /var/local/services.log &
+      args:
+        executable: /bin/bash
+      become: yes
+
+    - name: Check the dnsmasq process has started
+      # We do this in a separate shell task to the one that we started the
+      # process in so that we know that the process survived beyond that shell.
+      ansible.builtin.shell: |-
+        n=0
+        while [ $n -lt 3 ]; do
+          sleep 3
+          pgrep -f '^dnsmasq -d$' && 
+            echo 'dnsmasq    : Started' >> /var/local/services.log && break
+          let n=n+1
+        done
+        
+        if [ $n -eq 3 ]; then
+          echo 'dnsmasq    : Failed to start process' \
+            >> /var/local/services.log
+          exit 1
+        fi
+      args:
+        executable: /bin/bash
+
+  when: pgrep_result.rc == 1
diff --git a/my-roles/my_mail/tasks/start-dovecot.yml b/my-roles/my_mail/tasks/start-dovecot.yml
--- a/my-roles/my_mail/tasks/start-dovecot.yml
+++ b/my-roles/my_mail/tasks/start-dovecot.yml
@@ -5,29 +5,40 @@
 ---
 
 - name: Test if the dovecot process is running
-  ansible.builtin.shell: pgrep -f '^/usr/sbin/dovecot -F$' || true
+  ansible.builtin.shell: pgrep -f '^/usr/sbin/dovecot -F$'
   register: pgrep_result
   changed_when: false
+  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1
 
-- name: Start the dovecot process
-  ansible.builtin.shell: |-
-    echo 'dovecot    : Starting' >> '/var/local/services.log'
-    nohup dovecot -F 2>&1 | sed -u 's/^/dovecot    : /' \
-      >> '/var/local/services.log' &
+- block:
 
-    n=0
-    while [ $n -lt 3 ]; do
-      sleep 3
-      pgrep -f '^/usr/sbin/dovecot -F$' && \
-        echo 'dovecot    : Started' >> '/var/local/services.log' && break
-      let n=n+1
-    done
+    - name: Start the dovecot process
+      ansible.builtin.shell: |-
+        echo 'dovecot    : Starting' >> '/var/local/services.log'
+        nohup dovecot -F |& sed -u 's/^/dovecot    : /' \
+          &>> '/var/local/services.log' &
+      args:
+        executable: /bin/bash
+      become: yes
 
-    if [ $n -eq 3 ]; then
-      echo 'dovecot    : Failed to start process' \
-        >> /var/local/services.log
-    fi
-  args:
-    executable: /bin/bash
-  become: yes
-  when: not pgrep_result.stdout
+    - name: Check the dovecot process has started
+      # We do this in a separate shell task to the one that we started the
+      # process in so that we know that the process survived beyond that shell.
+      ansible.builtin.shell: |-
+        n=0
+        while [ $n -lt 3 ]; do
+          sleep 3
+          pgrep -f '^/usr/sbin/dovecot -F$' && \
+            echo 'dovecot    : Started' >> '/var/local/services.log' && break
+          let n=n+1
+        done
+
+        if [ $n -eq 3 ]; then
+          echo 'dovecot    : Failed to start process' \
+            >> /var/local/services.log
+          exit 1
+        fi
+      args:
+        executable: /bin/bash
+
+  when: pgrep_result.rc == 1
diff --git a/my-roles/my_mail_certificates/tasks/start-cron.yml b/my-roles/my_mail_certificates/tasks/start-cron.yml
--- a/my-roles/my_mail_certificates/tasks/start-cron.yml
+++ b/my-roles/my_mail_certificates/tasks/start-cron.yml
@@ -5,29 +5,40 @@
 ---
 
 - name: Test if the cron process is running
-  ansible.builtin.shell: pgrep -f '^cron -f$' || true
+  ansible.builtin.shell: pgrep -f '^cron -f$'
   register: pgrep_result
   changed_when: false
+  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1
 
-- name: Start the cron process
-  ansible.builtin.shell: |-
-    echo 'cron       : Starting' >> /var/local/services.log
-    nohup cron -f 2>&1 | sed -u 's/^/cron       : /' \
-      >> /var/local/services.log &
+- block:
 
+    - name: Start the cron process
+      ansible.builtin.shell: |-
+        echo 'cron       : Starting' >> /var/local/services.log
+        nohup cron -f |& sed -u 's/^/cron       : /' \
+          &>> /var/local/services.log &
+      args:
+        executable: /bin/bash
+      become: yes
+
+    - name: Check the cron process has started
+      # We do this in a separate shell task to the one that we started the
+      # process in so that we know that the process survived beyond that shell.
+      ansible.builtin.shell: |-
         n=0
-    while [ $n -lt 3 ]; do
-      sleep 3
-      pgrep -f '^cron -f$' && \
-        echo 'cron       : Started' >> /var/local/services.log && break
-      let n=n+1
-    done
-    
-    if [ $n -eq 3 ]; then
-      echo 'cron       : Failed to start process' \
-        >> /var/local/services.log
-    fi
-  args:
-    executable: /bin/bash
-  become: yes
-  when: not pgrep_result.stdout
+        while [ $n -lt 3 ]; do
+          sleep 3
+          pgrep -f '^cron -f$' && \
+            echo 'cron       : Started' >> /var/local/services.log && break
+          let n=n+1
+        done
+        
+        if [ $n -eq 3 ]; then
+          echo 'cron       : Failed to start process' \
+            >> /var/local/services.log
+          exit 1
+        fi
+      args:
+        executable: /bin/bash
+
+  when: pgrep_result.rc == 1
diff --git a/my-roles/my_mail_internal/tasks/start-fetchmail.yml b/my-roles/my_mail_internal/tasks/start-fetchmail.yml
--- a/my-roles/my_mail_internal/tasks/start-fetchmail.yml
+++ b/my-roles/my_mail_internal/tasks/start-fetchmail.yml
@@ -5,9 +5,10 @@
 ---
 
 - name: Test if the fetchmail process is running
-  ansible.builtin.shell: pgrep -f '^/usr/bin/fetchmail$' || true
+  ansible.builtin.shell: pgrep -f '^/usr/bin/fetchmail$'
   register: pgrep_result
   changed_when: false
+  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1
 
 - name: Test if fetchmail has been configured with mailservers
   ansible.builtin.command: ls /etc/fetchmailrc
@@ -15,15 +16,37 @@
   changed_when: false
   failed_when: fetchmailrc_exists.rc != 0 and fetchmailrc_exists.rc != 2
 
-- name: Start the fetchmail process if it isn't already running
-  ansible.builtin.shell: |-
-    echo 'fetchmail  : Starting' >> '/var/local/services.log'
-    nohup /usr/bin/fetchmail >> '/var/local/services.log' &
-    while true
-    do
-      sleep 3
-      pgrep -f '^/usr/bin/fetchmail$' && break
-    done
-    echo 'fetchmail  : Started' >> '/var/local/services.log'
-  become: yes
-  when: not pgrep_result.stdout and fetchmailrc_exists == 0
+- block:
+
+    - name: >-
+        Start the fetchmail process if it has been configured isn't already
+        running
+      ansible.builtin.shell: |-
+        echo 'fetchmail  : Starting' >> /var/local/services.log
+        nohup fetchmail |& sed -u 's/^/fetchmail  : /' \
+          &>> /var/local/services.log &
+      args:
+        executable: /bin/bash
+      become: yes
+
+    - name: Check the fetchmail process has started
+      # We do this in a separate shell task to the one that we started the
+      # process in so that we know that the process survived beyond that shell.
+      ansible.builtin.shell: |-
+        n=0
+        while [ $n -lt 3 ]; do
+          sleep 3
+          pgrep -f '^fetchmail$' && \
+            echo 'fetchmail  : Started' >> /var/local/services.log && break
+          let n=n+1
+        done
+
+        if [ $n -eq 3 ]; then
+          echo 'fetchmail  : Failed to start process' \
+            >> /var/local/services.log
+          exit 1
+        fi
+      args:
+        executable: /bin/bash
+
+  when: pgrep_result.rc == 1 and fetchmailrc_exists.rc == 0
diff --git a/my-roles/my_mta/tasks/start-exim.yml b/my-roles/my_mta/tasks/start-exim.yml
--- a/my-roles/my_mta/tasks/start-exim.yml
+++ b/my-roles/my_mta/tasks/start-exim.yml
@@ -5,29 +5,40 @@
 ---
 
 - name: Test if the exim process is running
-  ansible.builtin.shell: pgrep -f '^/usr/sbin/exim4 -bdf$' || true
+  ansible.builtin.shell: pgrep -f '^/usr/sbin/exim4 -bdf$'
   register: pgrep_result
   changed_when: false
+  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1
 
-- name: Start the exim process
-  ansible.builtin.shell: |-
-    echo 'exim       : Starting' >> /var/local/services.log
-    nohup /usr/sbin/exim4 -bdf 2>&1 | sed -u 's/^/exim       : /' \
-      >> /var/local/services.log &
+- block:
 
-    n=0
-    while [ $n -lt 3 ]; do
-      sleep 3
-      pgrep -f '^/usr/sbin/exim4 -bdf$' && \
-        echo 'exim       : Started' >> /var/local/services.log && break
-    let n=n+1
-    done
-    
-    if [ $n -eq 3 ]; then
-      echo 'exim       : Failed to start process' \
-        >> /var/local/services.log
-    fi
-  args:
-    executable: /bin/bash
-  become: yes
-  when: not pgrep_result.stdout
+    - name: Start the exim process
+      ansible.builtin.shell: |-
+        echo 'exim       : Starting' >> /var/local/services.log
+        nohup /usr/sbin/exim4 -bdf |& sed -u 's/^/exim       : /' \
+          &>> /var/local/services.log &
+      args:
+        executable: /bin/bash
+      become: yes
+
+    - name: Check the exim process has started
+      # We do this in a separate shell task to the one that we started the
+      # process in so that we know that the process survived beyond that shell.
+      ansible.builtin.shell: |-
+        n=0
+        while [ $n -lt 3 ]; do
+          sleep 3
+          pgrep -f '^/usr/sbin/exim4 -bdf$' && \
+            echo 'exim       : Started' >> /var/local/services.log && break
+        let n=n+1
+        done
+        
+        if [ $n -eq 3 ]; then
+          echo 'exim       : Failed to start process' \
+            >> /var/local/services.log
+          exit 1
+        fi
+      args:
+        executable: /bin/bash
+
+  when: pgrep_result.rc == 1
diff --git a/my-roles/my_reverse_proxy/tasks/start-nginx.yml b/my-roles/my_reverse_proxy/tasks/start-nginx.yml
--- a/my-roles/my_reverse_proxy/tasks/start-nginx.yml
+++ b/my-roles/my_reverse_proxy/tasks/start-nginx.yml
@@ -5,30 +5,41 @@
 ---
 
 - name: Test if the nginx process is running
-  ansible.builtin.shell: "\
-    pgrep -f '^nginx: master process nginx -g daemon off;$' || true"
+  ansible.builtin.shell: |-
+    pgrep -f '^nginx: master process nginx -g daemon off;$'
   register: pgrep_result
   changed_when: false
+  failed_when: pgrep_result.rc !=0 and pgrep_result.rc != 1
 
-- name: Start the nginx process
-  ansible.builtin.shell: |-
-    echo 'nginx      : Starting' >> '/var/local/services.log'
-    nohup nginx -g 'daemon off;' 2>&1 | sed -u 's/^/nginx      : /' \
-      >> '/var/local/servies.log' &
+- block:
 
-    n=0
-    while [ $n -lt 3 ]; do
-      sleep 3
-      pgrep -f '^nginx: master process' && \
-        echo 'nginx      : Started' >> '/var/local/services.log' && break
-      let n=n+1
-    done
+    - name: Start the nginx process
+      ansible.builtin.shell: |-
+        echo 'nginx      : Starting' >> '/var/local/services.log'
+        nohup nginx -g 'daemon off;' |& sed -u 's/^/nginx      : /' \
+          &>> '/var/local/servies.log' &
+      args:
+        executable: /bin/bash
+      become: yes
 
-    if [ $n -eq 3 ]; then
-      echo 'nginx      : Failed to start process' \
-        >> /var/local/services.log
-    fi
-  args:
-    executable: /bin/bash
-  become: yes
+    - name: Check the nginx process has started
+      # We do this in a separate shell task to the one that we started the
+      # process in so that we know that the process survived beyond that shell.
+      ansible.builtin.shell: |-
+        n=0
+        while [ $n -lt 3 ]; do
+          sleep 3
+          pgrep -f '^nginx: master process' && \
+            echo 'nginx      : Started' >> '/var/local/services.log' && break
+          let n=n+1
+        done
+
+        if [ $n -eq 3 ]; then
+          echo 'nginx      : Failed to start process' \
+            >> /var/local/services.log
+          exit 1
+        fi
+      args:
+        executable: /bin/bash
+
   when: not pgrep_result.stdout
diff --git a/my-roles/my_wordpress_apache/tasks/start-apache.yml b/my-roles/my_wordpress_apache/tasks/start-apache.yml
--- a/my-roles/my_wordpress_apache/tasks/start-apache.yml
+++ b/my-roles/my_wordpress_apache/tasks/start-apache.yml
@@ -5,32 +5,54 @@
 ---
 
 - name: Test if the apache2 process is running
-  ansible.builtin.shell: |-
-    pgrep -f '^apache2 -D FOREGROUND$' || true
+  ansible.builtin.shell: pgrep -f '^apache2 -D FOREGROUND$'
   register: pgrep_result
   changed_when: false
+  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1
 
-- name: Start the apache2 process
-  ansible.builtin.shell: |-
-    source /etc/apache2/envvars
+- block:
 
-    echo 'apache2    : Starting' >> '/var/local/services.log'
-    nohup apache2 -D FOREGROUND 2>&1 | sed -u 's/^/apache2    : /' \
-      >> '/var/local/servies.log' &
+    # If I introduce a nested block here for the common 'become: yes' on the
+    # next two tasks, then I get an error with the following message:
+    #
+    # ERROR! Unexpected Exception, this is probably a bug:
+    # 'Block' object has no attribute 'get_name'
 
-    n=0
-    while [ $n -lt 3 ]; do
-      sleep 3
-      pgrep -f '^apache2 -D FOREGROUND$' && \
-        echo 'apache2    : Started' >> '/var/local/services.log' && break
-      let n=n+1
-    done
+    - name: Create the Apache run directory
+      ansible.builtin.file:
+        path: /var/run/apache2
+        state: directory
+      become: yes
 
-    if [ $n -eq 3 ]; then
-      echo 'apache2    : Failed to start process' \
-        >> /var/local/services.log
-    fi
-  args:
-    executable: /bin/bash
-  become: yes
-  when: not pgrep_result.stdout
+    - name: Start the apache2 process
+      ansible.builtin.shell: |-
+        source /etc/apache2/envvars
+
+        echo 'apache2    : Starting' >> '/var/local/services.log'
+        nohup apache2 -D FOREGROUND |& sed -u 's/^/apache2    : /' \
+          &>> '/var/local/servies.log' &
+      args:
+        executable: /bin/bash
+      become: yes
+
+    - name: Check the apache2 process has started
+      # We do this in a separate shell task to the one that we started the
+      # process in so that we know that the process survived beyond that shell.
+      ansible.builtin.shell: |-
+        n=0
+        while [ $n -lt 3 ]; do
+          sleep 3
+          pgrep -f '^apache2 -D FOREGROUND$' && \
+            echo 'apache2    : Started' >> '/var/local/services.log' && break
+          let n=n+1
+        done
+
+        if [ $n -eq 3 ]; then
+          echo 'apache2    : Failed to start process' \
+            >> /var/local/services.log
+          exit 1
+        fi
+      args:
+        executable: /bin/bash
+
+  when: pgrep_result.rc == 1
